name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build and test
        run: ./mvnw clean test

      - name: Package application
        run: ./mvnw clean package
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar
